name: Deploy to EC2 (main)

on:
  push:
    branches:
      - tamar-project

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST_TAMAR }}
          username: ${{ secrets.EC2_USER_TAMAR }}
          key: ${{ secrets.EC2_SSH_KEY_TAMAR }}
          script: |
            cd ~/KonditoriaApp

            echo "Pull latest code"
            git pull origin tamar-project

            echo "Build client"
            cd react
            npm install
            npm run build

            echo "Deploy client to NGINX"
            sudo rm -rf /var/www/html/*
            sudo cp -r dist/* /var/www/html/

            echo "Restart server"
            cd ../node.js
            npm install
            sudo systemctl restart myapp

            echo "Deploy completed successfully"
