name: Deploy to EC2 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Write SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY_B64 }}" | base64 -d > $GITHUB_WORKSPACE/key.pem
          chmod 600 $GITHUB_WORKSPACE/key.pem

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key_path: ${{ github.workspace }}/key.pem
          script: |
            cd ~/KonditoriaApp

            echo "Pull latest code"
            git pull origin main

            echo "Build client"
            cd react
            npm install
            npm run build

            echo "Deploy client to NGINX"
            sudo rm -rf /var/www/html/*
            sudo cp -r dist/* /var/www/html/

            echo "Restart server"
            cd ../node.js
            npm install
            sudo systemctl restart myapp

            echo "Deploy completed successfully"
